import type { QuotaObservation } from './quota-observations';
import { invoke } from '@tauri-apps/api/core';
export type * from './reference-types';
import type { SessionReplayDetail } from './reference-types';
export const request = <T,>(method: string, args: unknown = {}) => invoke<T>('local_request', { method, args });
export const fetchSessionDetail = (path: string, query?: Query) => request<SessionReplayDetail>('replay', { path, query });
export const revealInFileManager = (path: string) => request<void>('reveal', { path });
export type Tokens = { input:number; cached:number; cacheWrite:number; output:number; reasoning:number };
export type Query = { start:number; end:number; agent:string|null; model:string|null; project:string|null; session:string|null; search:string; offsetMinutes:number; timeZone?:string };
export type Summary = { rangeStart?:number; rangeEnd?:number; key:string; label:string; tokens:Tokens; totalTokens:number; knownCostUsd:number; knownCostByComponent?:[number,number,number,number]; costUsd:number|null; unpricedEvents:number; unpricedTokens:number; events:number; firstTs:number; lastTs:number; agent:string; session:string; path:string };
export type ScanStatus = {agent:string; state:string; files:number; parsed:number; reused:number; events:number; malformedLines:number; errors:string[]; updatedAt:number; durationMs:number};
export type Activity = {id:string; agent:string; session:string; ts:number; name:string; path:string; line:number};
export type Dashboard = {query:Query; totals:Summary; models:Summary[]; projects:Summary[]; sessions:Summary[]; agents:Summary[]; days:Summary[]; months:Summary[]; series:Summary[]; bucketMs:number; tools:Record<string,number>; activityCount:number; quotas:QuotaObservation[]; quotaHistory:{total:number;items:QuotaObservation[]}; status:ScanStatus[]; availableModels:string[]; availableProjects:string[]; eventCount:number};
export type UsageEvent={id:string;agent:string;session:string;project:string;model:string;ts:number;tokens:Tokens;path:string;line:number};
export type EventPage={total:number;items:{event:UsageEvent;costUSD:number|null}[]};
export type Settings={port:number;refreshSeconds:number;roots:Record<string,string[]>;disabledAgents:string[]};
export type Bootstrap={settings:Settings;prices:string;dataDir:string;agents:[string,string][];autostart:boolean};
export type Status={running:boolean;scanning:boolean;stopping?:boolean;pid?:number};

export type ActivityPage={total:number;items:Activity[]};
